### List all bank accounts
GET http://localhost:3000/bank-accounts

@bank_account_id = d8cf2c42-7120-472f-8b34-b5769a082755

### Find a bank account by id
GET http://localhost:3000/bank-accounts/{{bank_account_id}}

### Create a new bank account
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
	"account_number": "1234-5",
	"owner_name": "John Doe"
}

### List all pix keys from a specific bank account
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys

### Create a new pix key for a specific bank account
POST http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys
Content-Type: application/json

{
	"kind": "email",
	"key": "johndoe@email.com"
}

### List all bank account transactions
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/transactions

### Create a new transaction for bank account
POST http://localhost:3000/bank-accounts/{{bank_account_id}}/transactions
Content-Type: application/json

{
	"pix_key_key": "johndoe@email.com",
	"pix_key_kind": "email",
	"description": "My transaction",
	"amount": 10.00
}