GET http://localhost:3000/bank-accounts

@bank_account_id = d8cf2c42-7120-472f-8b34-b5769a082755

###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}

### 
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
	"account_number": "1234-5",
	"owner_name": "John Doe"
}

###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys

### 
POST http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys
Content-Type: application/json

{
	"kind": "email",
	"key": "johndoe@email.com"
}
