services:
  # backend:
  #   build: .
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   volumes:
  #     - .:/home/node/app

  codebank-database:
    image: postgres:16-alpine
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql