services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest