services:
  # backend:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app

  codebank-database:
    image: postgres:16-alpine
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codebank
    ports:
      - "5433:5432"