services:
  # backend:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app

  codebank-database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgresman
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=nest